### ISSUE TITLE
[Feature Plan] Add clickable 'Total Users' for an export list of addresses

### ISSUE THREAD

**Issue by JSKitty** [stakecube/SCPscan#2]
Useful for airdrops, explorer data, statistical data, etc.

**Comment by JSKitty** [comment]
![image](https://user-images.githubusercontent.com/42538664/135138520-c3ffa929-756f-4ad1-a708-9c5c95ec0477.png)

Flow:
- Click the "Total Users" number.
- Modal pops up, with a single, large, read-only textbox, containing a list of **ALL unique** addresses.
- Optional Bonus: A "Copy" button to auto-copy all of the text to the clipboard?

**Comment by sc-9310** [comment]
The idea is good, but only possible as long as the number is really low. ETH has 170 M unqiue addresses (src: https://etherscan.io/chart/address) - will not be possible to load at a certain point.

**Comment by JSKitty** [comment]
Agreed, the first ~10k users will work fine, after that, I have ideas to implement numeric indexing, which will solve this issue fully and make 'compressing' a user list easy. 😄

**Comment by JSKitty** [comment]
Feature Plan resolved by @OfficialDevvCat in commit https://github.com/stakecube/SCPscan/commit/e569f1d2d7eded08ccb677860568fe9b3cf9ffc4
